### ISSUE TITLE
The user can change the patient information(site, patient sequence, trial name) before uploading the data, which causes the data saved under a wrong patient

### ISSUE THREAD

**Issue by MrC1rcle** [Image-X-Institute/The-Real-Time-Imaging-Database#25]
It's not a safe option to allow user change patient information. For example, a patient from center 1, which have a patient sequence of 2 and a TROG id of 0000001. When inputting the correct TROG id the correct information of this patient will show in the window. But the user still can change the information of this patient, like choosing center2 before uploading, then the data will be uploaded to center2 patient 2. 
Better not allow users have the ability to do that.

**Comment by ChandrimaSengupta** [comment]
Contentuploadertool will be used by the assigned RTs/physicists, so this should be fine. They will know the correct patient sequence and the TROG ID.
