### ISSUE TITLE
Gosford patient measured motion file paths

### ISSUE THREAD

**Issue by Frances000** [Image-X-Institute/The-Real-Time-Imaging-Database#50]
In Gosford Patient 2 fraction 5, instead of one fx5 folder, there are 2 nested a and b folders in fx5, but the current log lists "Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT02\Fx5\KIM-KV" as the path to images and a similar issue for path to logs in patient measured motion.

True directory path:
images:
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT02\Fx5\Fx5a\KIM-KV". 
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT02\Fx5\Fx5b\KIM-KV". 
log files:
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Measured Motion\PAT02\Fx5\Fx5a"
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Measured Motion\PAT02\Fx5\Fx5b"

For patient 3 fraction 5, the folders are also named according to a different convention, and there is a note that says the second folder of these is not useful. The folders are: 
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT03\Fx5\1703025,LARK_Fx05_2_230804_1555"
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT03\Fx5\1703025,LARK_Fx05_2_230804_1601"
"Y:\PRJ-RPL\2RESEARCH\1_ClinicalData\LARK\Gosford\Patient Images\PAT03\Fx5\1703025,LARK_Fx05_230804_1506"

For patient 0 fraction 0, there is no KIM log path (There is no directory that exists) but would it be possible to put in a placeholder (non-null value) so that the paths will not be misaligned? 

Thank you in advance for taking a look at this!

**Comment by Gahhh** [comment]
Gosford Patient 2 Fx5a and Fx5b - Fixed

Patient 3 fraction 5 - I dont know if we need to keep only one folder or change them to sub fractions

Patient 0 placeholder - Done, the placeholder is 'does not existing'.
