### ISSUE TITLE
Centroid File Path Showed as NULL

### ISSUE THREAD

**Issue by hotellonely** [Image-X-Institute/The-Real-Time-Imaging-Database#51]
Sample Query: http://_database_:8090/prescriptions?trial=SPARK
Sample Result:
...
"centroid_pres": NULL,
...

Expected Result:
"centroid_pres": _PATH TO CENTROID FILE_

**Comment by Gahhh** [comment]
This is because the patient folder name in CMN centre does not follow the template folder structure. The other center used _**PATxx**_ as patient folder name. In CMN, _**Patient X**_ has been used. So we need to change the patient folder name in CMN folder.
