### ISSUE TITLE
Westmead "kim_logs_path": null when "kv_images_path" not null

### ISSUE THREAD

**Issue by Frances000** [Image-X-Institute/The-Real-Time-Imaging-Database#52]
There are about 5 or 6 fractions in the Westmead LARK database where the kim_logs_path does not exist, but the kv_images_path does. Would it be possible to change the null there to 'Does not exist' or similar (same issue as the Gosford PAT00/Fx0) so that it can be aligned first and then removed?
Here is an example: 

      "kim_logs_path": null,
      "kim_threshold": null,
      "kv_images_path": "/LARK/Westmead/Patient Images/Patient 17/fx2/KIM-KV/",

 Thank you in advance!

**Comment by Gahhh** [comment]
For Westmead, the records are not accurate. I will scan the Westmead folder and update all records again
